source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.2'
use_frameworks!

target 'PinEntryView_Example' do
  pod 'PinEntryView', :path => '../'

  target 'PinEntryView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
